--[[
Title: code behind for page StressTestPage.html
Author(s): LiXizhi
Date: 2009/11/3
Desc:  script/apps/Aries/EmuUsers/StressTestPage.html
Use Lib:
-------------------------------------------------------

-------------------------------------------------------
]]

NPL.load("(gl)script/apps/Aries/EmuUsers/EmuUsers.lua");

local StressTestPage = {};
commonlib.setfield("MyCompany.Aries.StressTestPage", StressTestPage);

local dsEmuUsers = {
	-- {nid, password, nickname, pos_x, pos_y, pos_z}
};
function StressTestPage.DS_Func_EmuUsers(index)
	if(index == nil) then
		if (dsEmuUsers) then
			return #(dsEmuUsers);
		end	
	else
		return dsEmuUsers[index];
	end
end

local page;
function StressTestPage.OnInit()
	page = document:GetPageCtrl();
end

-- all users
local Users = {};

-- csv account
local csvAccount = nil;

-- start test
function StressTestPage.OnClickStart(name, values)
	local filename = values.stressTestFilepath;
	
	local xmlRoot = ParaXML.LuaXML_ParseFile(filename);
	if(xmlRoot) then
		local node, usersNode;
		-- read all users
		for node in commonlib.XPath.eachNode(xmlRoot, "/EmuDB/EmuUsers/user") do
			-- skip the current user
			local u = node.attr
			if(u and u.username~=Map3DSystem.User.Name) then
				local user = MyCompany.Aries.EmuUser:new({
					nid = u.username,
					password = u.password,
					worldpath = u.worldpath,
				});
				user.index = #Users + 1;
				Users[user.index] = user;
				
				user.OnSignedIn = function()
					local next_user = Users[user.index+1];
					if(next_user) then
						next_user:Start();
					end	
				end
				
				local agentNode
				for agentNode in commonlib.XPath.eachNode(node, "/playeragent") do
					local playeragent = {
						x = tonumber(agentNode.attr.x),
						y = tonumber(agentNode.attr.y),
						z = tonumber(agentNode.attr.z),
						facing = tonumber(agentNode.attr.facing),
						nickname = agentNode.attr.nickname,
						AssetFile = agentNode.attr.AssetFile,
						-- whether this is a dummy
						dummy = tonumber(agentNode.attr.dummy),
					} 
					user:UpdatePlayerAgent(playeragent);
					--commonlib.echo(u.playeragent);
				end
				
			end
		end
	end	
	
	Map3DSystem.App.Commands.Call("Help.DumpClientNetMsg", true);
	
	local user = Users[1]
	if(user) then
		user:Start();
	end
end

-- get current user account
function StressTestPage.GetCurrentUserAccount()
	if(csvAccount) then
		return csvAccount;
	end
	csvAccount = {};
	local filename = page:GetValue("accountFileName", nil);
	local file = ParaIO.open(filename, "r");
	if(file:IsValid()) then
		
		-- read a line 
		local line = file:readline();
		while(line) do
			local values = commonlib.fromCSV(line)
			local u = {nid = string.gsub(values[1], " ",""), password = string.gsub(values[2], " ",""), nickname=string.gsub(values[3], " ","")};
			csvAccount[#csvAccount + 1] = u;
			
			line = file:readline();
		end
		file:close();
	end
	return csvAccount;
end

-- clear all users
function StressTestPage.OnClickClearAllUsers()
	dsEmuUsers = {};
	page:Refresh();
end

-- Create New User
function StressTestPage.OnClickCreateNewUser()
	local user = {index = (#dsEmuUsers + 1)};
	
	local csvAccount = StressTestPage.GetCurrentUserAccount();
	local account = csvAccount[user.index];
	if (account) then
		user.nid = account.nid;
		user.password = account.password;
		user.nickname = account.nickname;
		user.pos_x, user.pos_y, user.pos_z = ParaScene.GetPlayer():GetPosition();
		user.number = user.index;
		-- insert to front
		commonlib.insertArrayItem(dsEmuUsers, 1, user)
		page:Refresh();
		-- dsEmuUsers[user.index] = user;
	end
end

-- on click to generate stress test emulation users file.
--  see config/Aries.StressTest.EmuUsersDB.xml for an example. 
function StressTestPage.OnClickGenerate(name, values)
	local filename = values.stressTestOutputPath;
	local worldpath = values.worldpath;
	local assetfile = values.assetfile;
	
	if(filename) then
		local file = ParaIO.open(filename, "w");
		if(file:IsValid()) then
			file:writeline("<!--auto generated by script/apps/Aries/EmuUsers/StressTestPage.html-->");
			file:writeline("<EmuDB>");
			file:writeline("<EmuUsers>");
				
			local index, user
			for index, user in ipairs(dsEmuUsers) do
				file:writeline(string.format([[<user username="%s" password="%s" worldpath="%s" server="" nickname="%s">]], user.nid, user.password, worldpath or "", user.nickname));
				file:writeline(string.format([[    <playeragent x="%.1f" z="%.1f" y="%.1f" facing="0" AssetFile="%s"/>]], user.pos_x, user.pos_z, user.pos_y, assetfile or ""));
				file:writeline("</user>")
			end
			
			file:writeline("</EmuUsers>");
			file:writeline("</EmuDB>");
			file:close();
			
			_guihelper.MessageBox(string.format("%d users stress test file is successfully generated to %s", #dsEmuUsers, filename))
		end
	end
	
end