--[[
Author(s): WangTian
Date: by LXZ 2008/2/4 : no longer used file. 
use the lib:
Note: call Map3DSystem.DB.ExportAllGroupsToAssetPackage() to export as asset file. 
------------------------------------------------------------
-- run below codes to export data to asset files. 
NPL.load("(gl)script/kids/3DMapSystemData/DBAssets_backup_old_assetfile.lua");
Map3DSystem.DB.ExportAllGroupsToAssetPackage();

it contains a manual definition of Map3DSystem.DB.Items and Map3DSystem.DB.Groups
one can now use Map3DSystem.DB.ExportAllGroupsToAssetPackage(); to export, please see DBAssets.lua 
Currently all assets are loaded by the asset application.Assets file are now in asset package format. 
see the asset application for more information.  
------------------------------------------------------------
]]

local L = CommonCtrl.Locale("KidsUI");

Map3DSystem.DB.Groups = {

	{
		["name"] = "Normal Model",
		["parent"] = "Root",
		["rootpath"] = "model/",
		["text"] = "普通模型", -- TODO: translation and the icon, text and tooltip set to normal model
		--icon = L"asset_icon_building",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/LargeBuilding.png",
		--text = L"asset_text_building",
		tooltip = L"asset_tooltip_building",
	},
	{
		["name"] = "NM_01building",
		["parent"] = "Normal Model",
		["rootpath"] = "model/01building/",
		["text"] = "建筑",
		--icon = L"asset_icon_building",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/LargeBuilding.png",
		--text = L"asset_text_building",
		tooltip = L"asset_tooltip_building",
	},
	{
		["name"] = "NM_02furniture",
		["parent"] = "Normal Model",
		["rootpath"] = "model/02furniture/",
		["text"] = "家具",
		--icon = L"asset_icon_furniture",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Furniture.png",
		--text = L"asset_text_furniture",
		tooltip = L"asset_tooltip_furniture",
	},
	{
		["name"] = "NM_03tools",
		["parent"] = "Normal Model",
		["rootpath"] = "model/03tools/",
		["text"] = "生活",
		--icon = L"asset_icon_everyday",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/SmallBuilding.png",
		--text = L"asset_text_everyday",
		tooltip = L"asset_tooltip_everyday",
	},
	{
		["name"] = "NM_04deco",
		["parent"] = "Normal Model",
		["rootpath"] = "model/04deco/",
		["text"] = "装饰物",
		--icon = L"asset_icon_makeup",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Board.png",
		--text = L"asset_text_makeup",
		tooltip = L"asset_tooltip_makeup",
	},
	{
		["name"] = "NM_05plants",
		["parent"] = "Normal Model",
		["rootpath"] = "model/05plants/",
		["text"] = "花草",
		--icon = L"asset_icon_grass",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Plants.png",
		--text = L"asset_text_grass",
		tooltip = L"asset_tooltip_grass",
	},
	{
		["name"] = "NM_06props",
		["parent"] = "Normal Model",
		["rootpath"] = "model/06props/",
		["text"] = "杂物",
		--icon = L"asset_icon_props",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Prop.png",
		--text = L"asset_text_props",
		tooltip = L"asset_tooltip_props",
	},
	{
		["name"] = "NM_07trees",
		["parent"] = "Normal Model",
		["rootpath"] = "model/05plants/",
		["text"] = "树木",
		--icon = L"asset_icon_trees",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Trees.png",
		--text = L"asset_text_trees",
		tooltip = L"asset_tooltip_trees",
	},
	
	
	{
		["name"] = "Normal Character",
		["parent"] = "Root",
		["rootpath"] = "character/",
		["text"] = "普通人物", -- TODO: translation and the icon, text and tooltip set to normal character
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "NC_01human",
		["parent"] = "Normal Character",
		["rootpath"] = "character/01human/",
		["text"] = "人物",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/NPC.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "NC_02animals",
		["parent"] = "Normal Character",
		["rootpath"] = "character/02animals/",
		["text"] = "动物",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Animal.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "NC_03vehicles",
		["parent"] = "Normal Character",
		["rootpath"] = "character/03vehicles/",
		["text"] = "交通工具",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Vehicle.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "NC_04particles",
		["parent"] = "Normal Character",
		["rootpath"] = "character/04particles/",
		["text"] = "粒子",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Particle.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "NC_05helpers",
		["parent"] = "Normal Character",
		["rootpath"] = "character/05helpers/",
		["text"] = "提示器",
		icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Prop.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "NC_06other",
		["parent"] = "Normal Character",
		["rootpath"] = "character/06other/",
		["text"] = "其他",
		icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Pet.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "CCS_01original",
		["parent"] = "Normal Character",
		["rootpath"] = "character/v3/",
		["text"] = "CCS_01original",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "CCS_02test",
		["parent"] = "Normal Character",
		["rootpath"] = "character/v3/",
		["text"] = "CCS_02test",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	
	
	{
		["name"] = "BCS",
		["parent"] = "Root",
		["rootpath"] = "model/v3/components/",
		["text"] = "BCS",  -- TODO: translation and the icon, text and tooltip set to BCS
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Chimney.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_01base",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/base/",
		["text"] = "地基",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Base.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_02block",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/block/",
		["text"] = "楼层",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Block.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_03blocktop",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/blocktop/",
		["text"] = "房顶",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Blocktop.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_04stairs",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/stairs/",
		["text"] = "楼梯",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Stairs.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_05door",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/door/",
		["text"] = "门",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Door.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_06window",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/window/",
		["text"] = "窗",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Window.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_07chimney",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/chimney/",
		["text"] = "烟囱",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Chimney.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	{
		["name"] = "BCS_08deco",
		["parent"] = "BCS",
		["rootpath"] = "model/v3/components/deco/",
		["text"] = "装饰",
		--icon = L"asset_icon_character",
		icon = "Texture/3DMapSystem/MainBarIcon/Creator/Deco.png",
		--text = L"asset_text_character",
		tooltip = L"asset_tooltip_character",
	},
	
	
	--{
		--["name"] = "CCS",
		--["parent"] = "Root",
		--["rootpath"] = "character/v3/",
		--["text"] = "CCS",  -- TODO: translation and the icon, text and tooltip set to CCS
		----icon = L"asset_icon_character",
		--icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	--{
		--["name"] = "CCS_01original",
		--["parent"] = "CCS",
		--["rootpath"] = "character/v3/",
		--["text"] = "CCS_01original",
		----icon = L"asset_icon_character",
		--icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	--{
		--["name"] = "CCS_02test",
		--["parent"] = "CCS",
		--["rootpath"] = "character/v3/",
		--["text"] = "CCS_02test",
		----icon = L"asset_icon_character",
		--icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	--
	--
	---- TODO: for My Favorites and My Wishlist, the data should be stored in a different directory
	--{
		--["name"] = "My Favorites",
		--["parent"] = "Root",
		--["rootpath"] = "user/Favorites/", -- TODO: implement the favorite
		--["text"] = "My Favorites",  -- TODO: translation and the icon, text and tooltip set to My Favorites
		----icon = L"asset_icon_character",
		--icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	---- test the levels
	--{
		--["name"] = "TestLvl2",
		--["parent"] = "My Favorites",
		--["rootpath"] = "character/v3/",
		--["text"] = "TestLvl2",
		----icon = L"asset_icon_character",
		--icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	--{
		--["name"] = "TestLvl3",
		--["parent"] = "My Favorites/TestLvl2",
		--["rootpath"] = "character/v3/",
		--["text"] = "TestLvl3",
		----icon = L"asset_icon_character",
		--icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	--{
		--["name"] = "TestLvl4",
		--["parent"] = "My Favorites/TestLvl2/TestLvl3",
		--["rootpath"] = "character/v3/",
		--["text"] = "TestLvl4",
		----icon = L"asset_icon_character",
		--icon = "Texture/3DMapSystem/MainBarIcon/Creator/Avatar.png",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	
	--{
		--["name"] = "My Wishlist",
		--["parent"] = "Root",
		--["rootpath"] = "user/Wishlist/", -- TODO: implement the wishlist
		--["text"] = "My Wishlist",  -- TODO: translation and the icon, text and tooltip set to My Wishlist
		--icon = L"asset_icon_character",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
	--
	--{
		--["name"] = "WishlistTest",
		--["parent"] = "My Wishlist",
		--["rootpath"] = "user/Wishlist/",
		--["text"] = "WishlistTest",
		--icon = L"asset_icon_character",
		----text = L"asset_text_character",
		--tooltip = L"asset_tooltip_character",
	--},
};

-- item database
Map3DSystem.DB.Items = 
{
  ["NM_01building"] = { -- "建筑"
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.35",
  ["Reserved2"] = "1.2",
  ["Price"]=0,
  ["IconAssetName"] = L"民房",
  ["ModelFilePath"] = "model/01building/v1/01house/mingfang/mingfang.x",
  ["IconFilePath"] = "model/01building/v1/01house/mingfang/mingfang.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.35",
  ["Reserved2"] = "1.2",
  ["Price"]=0,
  ["IconAssetName"] = L"民房",
  ["ModelFilePath"] = "model/01building/v1/01house/minfang2/minfang2.x",
  ["IconFilePath"] = "model/01building/v1/01house/minfang2/minfang2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.35",
  ["Reserved2"] = "1.2",
  ["Price"]=0,
  ["IconAssetName"] = L"民房",
  ["ModelFilePath"] = "model/01building/v1/01house/mingfang3/mingfang3.x",
  ["IconFilePath"] = "model/01building/v1/01house/mingfang3/mingfang3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.35",
  ["Reserved2"] = "1.2",
  ["Price"]=0,
  ["IconAssetName"] = L"民房",
  ["ModelFilePath"] = "model/01building/v1/01house/mingfang4/mingfang4.x",
  ["IconFilePath"] = "model/01building/v1/01house/mingfang4/mingfang4.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"民房",
  ["ModelFilePath"] = "model/01building/v1/01house/民房1.x",
  ["IconFilePath"] = "model/01building/v1/01house/民房1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"民房",
  ["ModelFilePath"] = "model/01building/v1/01house/民房2.x",
  ["IconFilePath"] = "model/01building/v1/01house/民房2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.35",
  ["Reserved2"] = "1.2",
  ["Price"]=0,
  ["IconAssetName"] = L"草房",
  ["ModelFilePath"] = "model/01building/v1/01house/farmhouse/farmhouse.x",
  ["IconFilePath"] = "model/01building/v1/01house/farmhouse/farmhouse.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"市场",
  ["ModelFilePath"] = "model/01building/v1/01house/市场.x",
  ["IconFilePath"] = "model/01building/v1/01house/市场.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"杂货铺",
  ["ModelFilePath"] = "model/01building/v1/01house/杂货铺.x",
  ["IconFilePath"] = "model/01building/v1/01house/杂货铺.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"药店",
  ["ModelFilePath"] = "model/01building/v1/01house/药店.x",
  ["IconFilePath"] = "model/01building/v1/01house/药店.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"民房1",
  ["ModelFilePath"] = "model/06props/v1/zawu/zawu1.x",
  ["IconFilePath"] = "model/06props/v1/zawu/zawu1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.35",
  ["Reserved2"] = "1.2",
  ["Price"]=10,
  ["IconAssetName"] = L"古老银行",
  ["ModelFilePath"] = "model/01building/v1/01house/oldbank/oldbank.x",
  ["IconFilePath"] = "model/01building/v1/01house/oldbank/oldbank.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"酒馆",
  ["ModelFilePath"] = "model/01building/v1/01house/酒馆.x",
  ["IconFilePath"] = "model/01building/v1/01house/酒馆.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"风车",
  ["ModelFilePath"] = "model/01building/v1/01house/windwheel/windwheel.x",
  ["IconFilePath"] = "model/01building/v1/01house/windwheel/windwheel.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"风车",
  ["ModelFilePath"] = "model/01building/v1/01house/windwheel/windwheel1.x",
  ["IconFilePath"] = "model/01building/v1/01house/windwheel/windwheel1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"码头",
  ["ModelFilePath"] = "model/01building/v1/01house/码头.x",
  ["IconFilePath"] = "model/01building/v1/01house/码头.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.3",
  ["Reserved2"] = "1.2",
  ["Price"]=50,
  ["IconAssetName"] = L"哨塔",
  ["ModelFilePath"] = "model/06props/shared/pops/哨塔.x",
  ["IconFilePath"] = "model/06props/shared/pops/哨塔.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"水车",
  ["ModelFilePath"] = "model/06props/shared/pops/shuiche.x",
  ["IconFilePath"] = "model/06props/shared/pops/shuiche.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"高脚屋",
  ["ModelFilePath"] = "model/01building/v1/01house/高脚屋2.x",
  ["IconFilePath"] = "model/01building/v1/01house/高脚屋2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"马棚",
  ["ModelFilePath"] = "model/01building/v1/01house/马棚.x",
  ["IconFilePath"] = "model/01building/v1/01house/马棚.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"城镇中心",
  ["ModelFilePath"] = "model/01building/v1/01house/城镇中心.x",
  ["IconFilePath"] = "model/01building/v1/01house/城镇中心.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.35",
  ["Reserved2"] = "1.2",
  ["IconAssetName"] = L"教堂",
  ["Price"]=50,
  ["ModelFilePath"] = "model/01building/v1/01house/fane/fane.x",
  ["IconFilePath"] = "model/01building/v1/01house/fane/fane.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"树屋",
  ["ModelFilePath"] = "model/01building/v1/01house/树屋.x",
  ["IconFilePath"] = "model/01building/v1/01house/树屋.x.png",
}
,
 {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"城堡",
  ["ModelFilePath"] = "model/01building/v1/01house/castle/castle.x",
  ["IconFilePath"] = "model/01building/v1/01house/castle/castle.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"木桥",
  ["ModelFilePath"] = "model/01building/v1/02other/brigde/木桥2_v.x",
  ["IconFilePath"] = "model/01building/v1/02other/brigde/木桥2.x.png",
}
,
}
,
  ["NM_02furniture"] = { -- "家具"
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"小床",
  ["ModelFilePath"] = "model/06props/shared/pops/xiaochuang.x",
  ["IconFilePath"] = "model/06props/shared/pops/xiaochuang.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"桌子",
  ["ModelFilePath"] = "model/06props/shared/pops/桌子1.x",
  ["IconFilePath"] = "model/06props/shared/pops/桌子1.x.png",
}
,
 {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"桌子",
  ["ModelFilePath"] = "model/02furniture/v1/glasstable.x",
  ["IconFilePath"] = "model/02furniture/v1/glasstable.x.png",
}
,
 {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"石凳",
  ["ModelFilePath"] = "model/06props/shared/pops/石凳1.x",
  ["IconFilePath"] = "model/06props/shared/pops/石凳1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"长椅",
  ["ModelFilePath"] = "model/06props/v1/chair/chair.x",
  ["IconFilePath"] = "model/06props/v1/chair/chair.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"长椅",
  ["ModelFilePath"] = "model/02furniture/v1/chair.x",
  ["IconFilePath"] = "model/02furniture/v1/chair.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"长椅",
  ["ModelFilePath"] = "model/02furniture/v1/chair2.x",
  ["IconFilePath"] = "model/02furniture/v1/chair2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"垃圾桶",
  ["ModelFilePath"] = "model/06props/v1/garbagecan/garbagecan.x",
  ["IconFilePath"] = "model/06props/v1/garbagecan/garbagecan.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"电视机",
  ["ModelFilePath"] = "model/02furniture/v1/tv/tv.x",
  ["IconFilePath"] = "model/02furniture/v1/tv/tv.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"微波炉",
  ["ModelFilePath"] = "model/02furniture/v1/weibolu/weibolu.x",
  ["IconFilePath"] = "model/02furniture/v1/weibolu/weibolu.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"计算机",
  ["ModelFilePath"] = "model/02furniture/v1/computer/computer.x",
  ["IconFilePath"] = "model/02furniture/v1/computer/computer.x.png",
}
,
}
,
  ["NM_03tools"] = { -- "生活"
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"宠物屋",
  ["ModelFilePath"] = "model/01building/v1/02other/doghouse/宠物屋.x",
  ["IconFilePath"] = "model/01building/v1/02other/doghouse/宠物屋.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"茅草亭",
  ["ModelFilePath"] = "model/06props/shared/pops/maocaoting.x",
  ["IconFilePath"] = "model/06props/shared/pops/maocaoting.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"水井",
  ["ModelFilePath"] = "model/06props/shared/pops/水井.x",
  ["IconFilePath"] = "model/06props/shared/pops/水井.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"信箱",
  ["ModelFilePath"] = "model/03tools/v1/post/信箱.x",
  ["IconFilePath"] = "model/03tools/v1/post/信箱.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"木笼",
  ["ModelFilePath"] = "model/06props/v1/woodcage/木头笼子.x",
  ["IconFilePath"] = "model/06props/v1/woodcage/木头笼子.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"桶",
  ["ModelFilePath"] = "model/06props/v1/barrel/桶.x",
  ["IconFilePath"] = "model/06props/v1/barrel/桶.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"瓶子",
  ["ModelFilePath"] = "model/06props/v1/wases/瓶子_a.x",
  ["IconFilePath"] = "model/06props/v1/wases/瓶子_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"盘子",
  ["ModelFilePath"] = "model/06props/v1/dish/盘子_a.x",
  ["IconFilePath"] = "model/06props/v1/dish/盘子_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"碗",
  ["ModelFilePath"] = "model/06props/v1/bowl/碗_a.x",
  ["IconFilePath"] = "model/06props/v1/bowl/碗_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"木桶",
  ["ModelFilePath"] = "model/06props/shared/pops/木桶.x",
  ["IconFilePath"] = "model/06props/shared/pops/木桶.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"木桶",
  ["ModelFilePath"] = "model/06props/shared/pops/木桶2.x",
  ["IconFilePath"] = "model/06props/shared/pops/木桶2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"桶",
  ["ModelFilePath"] = "model/06props/shared/pops/桶.x",
  ["IconFilePath"] = "model/06props/shared/pops/桶.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"箱子",
  ["ModelFilePath"] = "model/06props/shared/pops/xiangzi1.x",
  ["IconFilePath"] = "model/06props/shared/pops/xiangzi1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"箱子",
  ["ModelFilePath"] = "model/06props/shared/pops/xiangzi2.x",
  ["IconFilePath"] = "model/06props/shared/pops/xiangzi2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"箱子",
  ["ModelFilePath"] = "model/06props/shared/pops/xiangzi3.x",
  ["IconFilePath"] = "model/06props/shared/pops/xiangzi3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"箱子",
  ["ModelFilePath"] = "model/06props/shared/pops/箱子.x",
  ["IconFilePath"] = "model/06props/shared/pops/箱子.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"箱子",
  ["ModelFilePath"] = "model/06props/shared/pops/箱子2.x",
  ["IconFilePath"] = "model/06props/shared/pops/箱子2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"箱子",
  ["ModelFilePath"] = "model/06props/shared/pops/箱子3.x",
  ["IconFilePath"] = "model/06props/shared/pops/箱子3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"箱子",
  ["ModelFilePath"] = "model/06props/shared/pops/箱子4.x",
  ["IconFilePath"] = "model/06props/shared/pops/箱子4.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"码头",
  ["ModelFilePath"] = "model/01building/v1/01house/码头2.x",
  ["IconFilePath"] = "model/01building/v1/01house/码头2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"绳子",
  ["ModelFilePath"] = "model/06props/v1/rope/绳子1_a.x",
  ["IconFilePath"] = "model/06props/v1/rope/绳子1_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"绳子",
  ["ModelFilePath"] = "model/06props/v1/rope/绳子2_a.x",
  ["IconFilePath"] = "model/06props/v1/rope/绳子2_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"小舟",
  ["ModelFilePath"] = "model/03tools/v1/bateau/小舟.x",
  ["IconFilePath"] = "model/03tools/v1/bateau/小舟.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"船浆",
  ["ModelFilePath"] = "model/03tools/v1/bateau/小舟船浆.x",
  ["IconFilePath"] = "model/03tools/v1/bateau/小舟船浆.x.png",
}
,
 {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"海盗船",
  ["ModelFilePath"] = "model/03tools/v1/ship/Pirate ship_v.x",
  ["IconFilePath"] = "model/03tools/v1/ship/Pirate ship_v.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"帆船",
  ["ModelFilePath"] = "model/03tools/v1/fanchuan/帆船_v.x",
  ["IconFilePath"] = "model/03tools/v1/fanchuan/帆船_v.x.png",
}
,
}
,
  ["NM_04deco"] = { -- "装饰"
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.3",
  ["Reserved2"] = "1.2",
  ["Price"]=0,
  ["IconAssetName"] = L"旗子",
  ["ModelFilePath"] = "model/06props/shared/pops/flag_a.x",
  ["IconFilePath"] = "model/06props/shared/pops/flag_a.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"云彩",
  ["ModelFilePath"] = "model/02furniture/v1/yun/yun.x",
  ["IconFilePath"] = "model/02furniture/v1/yun/yun.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"路灯",
  ["ModelFilePath"] = "model/06props/shared/pops/路灯1.x",
  ["IconFilePath"] = "model/06props/shared/pops/路灯1.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.3",
  ["Reserved2"] = "1.2",
  ["Price"]=10,
  ["IconAssetName"] = L"灯笼",
  ["ModelFilePath"] = "model/06props/shared/pops/灯笼.x",
  ["IconFilePath"] = "model/06props/shared/pops/灯笼.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.3",
  ["Reserved2"] = "1.2",
  ["Price"]=10,
  ["IconAssetName"] = L"传送站",
  ["ModelFilePath"] = "model/06props/shared/pops/传送站.x",
  ["IconFilePath"] = "model/06props/shared/pops/传送站.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.3",
  ["Reserved2"] = "1.2",
  ["Price"]=10,
  ["IconAssetName"] = L"喷泉",
  ["ModelFilePath"] = "model/06props/shared/pops/喷泉.x",
  ["IconFilePath"] = "model/06props/shared/pops/喷泉.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"烤鸡",
  ["ModelFilePath"] = "model/06props/v1/kaoji/kaoji.x",
  ["IconFilePath"] = "model/06props/v1/kaoji/kaoji.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"烤羊",
  ["ModelFilePath"] = "model/06props/v1/kaoyang/ARRUIL.x",
  ["IconFilePath"] = "model/06props/v1/kaoyang/ARRUIL.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"篝火",
  ["ModelFilePath"] = "model/06props/shared/fire/fire_p.x",
  ["IconFilePath"] = "model/06props/shared/fire/fire_p.x.png",
}
,
 {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"火堆",
  ["ModelFilePath"] = "model/06props/shared/pops/火堆1.x",
  ["IconFilePath"] = "model/06props/shared/pops/火堆1.x.png",
}
,
 {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"气球",
  ["ModelFilePath"] = "model/06props/v1/balloon/气球.x",
  ["IconFilePath"] = "model/06props/v1/balloon/气球.x.png",
}
,
{
  ["Reserved4"] = "R4",
  ["Reserved3"] = "1",
  ["Reserved1"] = "0.3",
  ["Reserved2"] = "1.2",
  ["Price"]=10,
  ["IconAssetName"] = L"方向牌",
  ["ModelFilePath"] = "model/06props/shared/pops/方向牌.x",
  ["IconFilePath"] = "model/06props/shared/pops/方向牌.x.png",
}
,
 {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = "board 画板",--TODO
  ["ModelFilePath"] = "model/06props/shared/pops/Instructions.x",
  ["IconFilePath"] = "model/06props/shared/pops/Instructions.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = "board 画板",--TODO
  ["ModelFilePath"] = "model/06props/shared/pops/guanggaopai.x",
  ["IconFilePath"] = "model/06props/shared/pops/guanggaopai.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = "board 画板",--TODO
  ["ModelFilePath"] = "model/06props/shared/pops/huaban.x",
  ["IconFilePath"] = "model/06props/shared/pops/huaban.x.png",
}
,
}
,
  ["NM_05plants"] = { -- "花草"
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"绿色灌木",
  ["ModelFilePath"] = "model/05plants/01flower/03grass/草1_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/03grass/草1_a_v.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"绿色灌木",
  ["ModelFilePath"] = "model/05plants/03shrub/绿色灌木1_a.x",
  ["IconFilePath"] = "model/05plants/03shrub/绿色灌木1_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"绿色灌木",
  ["ModelFilePath"] = "model/05plants/03shrub/绿色灌木2_a.x",
  ["IconFilePath"] = "model/05plants/03shrub/绿色灌木2_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"绿色灌木",
  ["ModelFilePath"] = "model/05plants/03shrub/绿色灌木3_a.x",
  ["IconFilePath"] = "model/05plants/03shrub/绿色灌木3_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"大蘑菇",
  ["ModelFilePath"] = "model/05plants/04other/大蘑菇1.x",
  ["IconFilePath"] = "model/05plants/04other/大蘑菇1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"大蘑菇",
  ["ModelFilePath"] = "model/05plants/04other/大蘑菇2.x",
  ["IconFilePath"] = "model/05plants/04other/大蘑菇2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"大蘑菇",
  ["ModelFilePath"] = "model/05plants/04other/大蘑菇3.x",
  ["IconFilePath"] = "model/05plants/04other/大蘑菇3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"大蘑菇",
  ["ModelFilePath"] = "model/05plants/04other/大蘑菇4.x",
  ["IconFilePath"] = "model/05plants/04other/大蘑菇4.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower001_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower001_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower002_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower002_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower003_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower003_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower004_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower004_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower005_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower005_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower006_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower006_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower007_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower007_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower008_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower008_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower009_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower009_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower009b_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower009b_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower009c_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower009c_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower010_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower010_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower011_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower011_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower012_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower012_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/01flower/flower013_a_v.x",
  ["IconFilePath"] = "model/05plants/01flower/01flower/flower013_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"花草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草11_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草11_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"花草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草12_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草12_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"花草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草13.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草13.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"花草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草15_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草15_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"花草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草28_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草28_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"花草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草30_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草30_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"花草群",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草群1_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草群1_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"花草群",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草群2_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草群2_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"花草群",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草群4_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草群4_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"花草群",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草群8_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草群8_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"花草群",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草群9_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草群9_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草19_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草19_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"草",
  ["ModelFilePath"] = "model/05plants/01flower/02flower/花草20_a.x",
  ["IconFilePath"] = "model/05plants/01flower/02flower/花草20_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"仙人掌",
  ["ModelFilePath"] = "model/05plants/03shrub/xianrenzhang/仙人掌01_a.x",
  ["IconFilePath"] = "model/05plants/03shrub/xianrenzhang/仙人掌01_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"仙人掌",
  ["ModelFilePath"] = "model/05plants/03shrub/xianrenzhang/仙人掌14_a.x",
  ["IconFilePath"] = "model/05plants/03shrub/xianrenzhang/仙人掌14_a.x.png",
}
,
}
,
  ["NM_06props"] = { -- "杂物"
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"围栏",
  ["ModelFilePath"] = "model/06props/shared/pops/weilan.x",
  ["IconFilePath"] = "model/06props/shared/pops/weilan.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"围栏",
  ["ModelFilePath"] = "model/06props/shared/pops/weilan4.x",
  ["IconFilePath"] = "model/06props/shared/pops/weilan4.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"围栏",
  ["ModelFilePath"] = "model/06props/shared/pops/weilan5.x",
  ["IconFilePath"] = "model/06props/shared/pops/weilan5.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"围栏",
  ["ModelFilePath"] = "model/06props/shared/pops/weilan6.x",
  ["IconFilePath"] = "model/06props/shared/pops/weilan6.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"栅栏",
  ["ModelFilePath"] = "model/06props/shared/pops/栅栏.x",
  ["IconFilePath"] = "model/06props/shared/pops/栅栏.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"栅栏",
  ["ModelFilePath"] = "model/06props/shared/pops/栅栏3.x",
  ["IconFilePath"] = "model/06props/shared/pops/栅栏3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"栅栏",
  ["ModelFilePath"] = "model/06props/shared/pops/栅栏4.x",
  ["IconFilePath"] = "model/06props/shared/pops/栅栏4.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"栅栏",
  ["ModelFilePath"] = "model/06props/shared/pops/栅栏5.x",
  ["IconFilePath"] = "model/06props/shared/pops/栅栏5.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"石头",
  ["ModelFilePath"] = "model/06props/shared/01stone/shitou2.x",
  ["IconFilePath"] = "model/06props/shared/01stone/shitou2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"石头",
  ["ModelFilePath"] = "model/06props/shared/01stone/shitou3.x",
  ["IconFilePath"] = "model/06props/shared/01stone/shitou3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"石头",
  ["ModelFilePath"] = "model/06props/shared/pops/shitou1.x",
  ["IconFilePath"] = "model/06props/shared/pops/shitou1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"大围栏石",
  ["ModelFilePath"] = "model/06props/shared/01stone/大围栏石1.x",
  ["IconFilePath"] = "model/06props/shared/01stone/大围栏石1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"大围栏石",
  ["ModelFilePath"] = "model/06props/shared/01stone/大围栏石2.x",
  ["IconFilePath"] = "model/06props/shared/01stone/大围栏石2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"大围栏石",
  ["ModelFilePath"] = "model/06props/shared/01stone/大围栏石3.x",
  ["IconFilePath"] = "model/06props/shared/01stone/大围栏石3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"小围栏石",
  ["ModelFilePath"] = "model/06props/shared/01stone/小围栏石2.x",
  ["IconFilePath"] = "model/06props/shared/01stone/小围栏石2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"小围栏石",
  ["ModelFilePath"] = "model/06props/shared/01stone/小围栏石3.x",
  ["IconFilePath"] = "model/06props/shared/01stone/小围栏石3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"石头",
  ["ModelFilePath"] = "model/06props/shared/01stone/shitou.x",
  ["IconFilePath"] = "model/06props/shared/01stone/shitou.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"喷泉",
  ["ModelFilePath"] = "model/06props/shared/penquan/penquan_t_d_a.x",
  ["IconFilePath"] = "model/06props/shared/penquan/penquan_t_d_a.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"马车拖车",
  ["ModelFilePath"] = "model/03tools/v1/dragcar/马车的拖车载货.x",
  ["IconFilePath"] = "model/03tools/v1/dragcar/马车的拖车载货.x.png",
}
,
}
,
  ["NM_07trees"] = { -- "树木"
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01树/树11.x",
  ["IconFilePath"] = "model/05plants/02tree/01树/树11.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01树/树13.x",
  ["IconFilePath"] = "model/05plants/02tree/01树/树13.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"椰子树",
  ["ModelFilePath"] = "model/05plants/02tree/06椰子树/椰树_new1_v.x",
  ["IconFilePath"] = "model/05plants/02tree/06椰子树/椰树_new1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"椰子树",
  ["ModelFilePath"] = "model/05plants/02tree/06椰子树/椰树_new2_v.x",
  ["IconFilePath"] = "model/05plants/02tree/06椰子树/椰树_new2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"竹林",
  ["ModelFilePath"] = "model/05plants/02tree/05竹林/竹群1.x",
  ["IconFilePath"] = "model/05plants/02tree/05竹林/竹群1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"竹林",
  ["ModelFilePath"] = "model/05plants/02tree/05竹林/竹群2.x",
  ["IconFilePath"] = "model/05plants/02tree/05竹林/竹群2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"竹林",
  ["ModelFilePath"] = "model/05plants/02tree/05竹林/竹群3.x",
  ["IconFilePath"] = "model/05plants/02tree/05竹林/竹群3.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"柳树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree01/tree01_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree01/tree01.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"柳树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree01/tree011_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree01/tree011.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree02/tree020_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree02/tree020.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree02/tree021_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree02/tree021.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree02/tree022_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree02/tree022.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree02/tree023_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree02/tree023.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree04/tree04_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree04/tree04.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree04/tree05_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree04/tree05.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"树",
  ["ModelFilePath"] = "model/05plants/02tree/01tree/tree03/tree03_v.x",
  ["IconFilePath"] = "model/05plants/02tree/01tree/tree03/tree03.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=0,
  ["IconAssetName"] = L"松树",
  ["ModelFilePath"] = "model/05plants/02tree/04曲松/松树1.x",
  ["IconFilePath"] = "model/05plants/02tree/04曲松/松树1.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=10,
  ["IconAssetName"] = L"松树",
  ["ModelFilePath"] = "model/05plants/02tree/04曲松/松树2.x",
  ["IconFilePath"] = "model/05plants/02tree/04曲松/松树2.x.png",
}
,
  {
  ["Reserved4"] = "R4",
  ["Reserved3"] = "R3",
  ["Reserved1"] = "R1",
  ["Reserved2"] = "R2",
  ["Price"]=50,
  ["IconAssetName"] = L"松树",
  ["ModelFilePath"] = "model/05plants/02tree/04曲松/松树5.x",
  ["IconFilePath"] = "model/05plants/02tree/04曲松/松树5.x.png",
}
,
}
,
  ["NC_01human"] = { -- "人物"
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"龙",
	  ["ModelFilePath"] = "character/v1/01human/long/long.x",
	  ["IconFilePath"] = "character/v1/01human/long/long.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=10,
	  ["IconAssetName"] = L"Eva",
	  ["ModelFilePath"] = "character/v1/01human/eva/eva1.x",
	  ["IconFilePath"] = "character/v1/01human/eva/eva1.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"玛丽亚",
	  ["ModelFilePath"] = "character/v1/01human/erluoshi/erluoshi.x",
	  ["IconFilePath"] = "character/v1/01human/erluoshi/erluoshi.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=10,
	  ["IconAssetName"] = L"丹尼",
	  ["ModelFilePath"] = "character/v1/01human/danni/danni.x",
	  ["IconFilePath"] = "character/v1/01human/danni/danni.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"baru",
	  ["ModelFilePath"] = "character/v1/01human/baru/baru.x",
	  ["IconFilePath"] = "character/v1/01human/baru/baru.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"男孩",
	  ["ModelFilePath"] = "character/v1/01human/boy/boy.x",
	  ["IconFilePath"] = "character/v1/01human/boy/boy.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"女孩",
	  ["ModelFilePath"] = "character/v1/01human/girl/girl.x",
	  ["IconFilePath"] = "character/v1/01human/girl/girl.x.png",
	}
	,
  },
  ["NC_02animals"] = { -- "动物"
   {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"青蛙",
	  ["ModelFilePath"] = "character/v1/02animals/01land/guagua/guagua.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/guagua/guagua.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"蜘蛛",
	  ["ModelFilePath"] = "character/v1/02animals/01land/chengcheng/cheng.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/chengcheng/cheng.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=10,
	  ["IconAssetName"] = L"小狗",
	  ["ModelFilePath"] = "character/v1/02animals/01land/chevalier/chevalier.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/chevalier/chevalier.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=10,
	  ["IconAssetName"] = L"小猪",
	  ["ModelFilePath"] = "character/v1/02animals/01land/luobin/luobin.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/luobin/luobin.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"蛇",
	  ["ModelFilePath"] = "character/v1/02animals/01land/snake/snake.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/snake/snake.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"松鼠",
	  ["ModelFilePath"] = "character/v1/02animals/01land/songshu/shongshu.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/songshu/shongshu.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"蜗牛",
	  ["ModelFilePath"] = "character/v1/02animals/01land/woniu/woniu.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/woniu/woniu.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"蝎子",
	  ["ModelFilePath"] = "character/v1/02animals/01land/xiezi/xiezi.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/xiezi/xiezi.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"小狗",
	  ["ModelFilePath"] = "character/v1/02animals/01land/dog/dog.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/dog/dog.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"小牛",
	  ["ModelFilePath"] = "character/v1/02animals/01land/niu/niu.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/niu/niu.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"小猪",
	  ["ModelFilePath"] = "character/v1/02animals/01land/pigmen/pig.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/pigmen/pig.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"兔子",
	  ["ModelFilePath"] = "character/v1/02animals/01land/cony1/cony1.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/cony1/cony1.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"小猫",
	  ["ModelFilePath"] = "character/v1/02animals/01land/cat/cat.x",
	  ["IconFilePath"] = "character/v1/02animals/01land/cat/cat.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"小鱼",
	  ["ModelFilePath"] = "character/v1/02animals/03sea/fish/fish01.x",
	  ["IconFilePath"] = "character/v1/02animals/03sea/fish/fish01.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"小鱼",
	  ["ModelFilePath"] = "character/v1/02animals/03sea/fish04/fish04.x",
	  ["IconFilePath"] = "character/v1/02animals/03sea/fish04/fish04.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=10,
	  ["IconAssetName"] = L"小鱼",
	  ["ModelFilePath"] = "character/v1/02animals/03sea/fish05/fish05.x",
	  ["IconFilePath"] = "character/v1/02animals/03sea/fish05/fish05.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["IconAssetName"] = L"海星",
	  ["Price"]=0,
	  ["ModelFilePath"] = "character/v1/02animals/03sea/haixing03/haixing03.x",
	  ["IconFilePath"] = "character/v1/02animals/03sea/haixing03/haixing03.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["IconAssetName"] = L"蝴蝶",
	  ["Price"]=0,
	  ["ModelFilePath"] = "character/v1/02animals/02fly/hudie01/hudie01.x",
	  ["IconFilePath"] = "character/v1/02animals/02fly/hudie01/hudie01.x.png",
	}
	,
  },
  ["NC_03vehicles"] = { -- "交通工具"
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"秋千",
	  ["ModelFilePath"] = "character/v1/03vehicles/01land/qiuqian/qiuqian.x",
	  ["IconFilePath"] = "character/v1/03vehicles/01land/qiuqian/qiuqian.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "1",
	  ["Reserved2"] = "0.2",
	  ["IconAssetName"] = L"直升机",
	  ["Price"]=0,
	  ["ModelFilePath"] = "character/v1/03vehicles/02fly/heli/heli01.x",
	  ["IconFilePath"] = "character/v1/03vehicles/02fly/heli/heli01.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=0,
	  ["IconAssetName"] = L"卡丁车",
	  ["ModelFilePath"] = "character/v1/03vehicles/01land/kadingche/ka.x",
	  ["IconFilePath"] = "character/v1/03vehicles/01land/kadingche/ka.x.png",
	}
	,
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.5",
	  ["Reserved2"] = "0.3",
	  ["Price"]=10,
	  ["IconAssetName"] = L"帆船",
	  ["ModelFilePath"] = "character/v1/03vehicles/03sea/Pirate ship/Pirate ship NPC.x",
	  ["IconFilePath"] = "character/v1/03vehicles/03sea/Pirate ship/Pirate ship NPC.x.png",
	}
	,
  },
  ["NC_04particles"] = { -- "粒子"
  
  },
  ["NC_05helpers"] = { -- "提示器"
  
  },
  ["NC_06other"] = { -- "其他"
	  {
	  ["Reserved4"] = "R4",
	  ["Reserved3"] = "1",
	  ["Reserved1"] = "0.3",
	  ["Reserved2"] = "1.2",
	  ["Price"]=50,
	  ["IconAssetName"] = L"宝箱",
	  ["ModelFilePath"] = "character/v1/06other/baoxiang/baoxiang.x",
	  ["IconFilePath"] = "character/v1/06other/baoxiang/baoxiang.x.png",
	}
	,
  },
  
  
  ---- BCS components
  --["BCS_01base"] = { -- 地基
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "地基1",
	  --["ModelFilePath"] = "model/01building/V3/components/base/base01/base01.x",
	  --["IconFilePath"] = "model/01building/V3/components/base/base01/base01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "地基2",
	  --["ModelFilePath"] = "model/01building/V3/components/base/base02/base02.x",
	  --["IconFilePath"] = "model/01building/V3/components/base/base02/base02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "地基3",
	  --["ModelFilePath"] = "model/01building/V3/components/base/base03/base03.x",
	  --["IconFilePath"] = "model/01building/V3/components/base/base03/base03.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "亭子1",
	  --["ModelFilePath"] = "model/01building/V3/components/base/tingzi01/tingzi01.x",
	  --["IconFilePath"] = "model/01building/V3/components/base/tingzi01/tingzi01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "亭子2",
	  --["ModelFilePath"] = "model/01building/V3/components/base/tingzi02/tingzi02.x",
	  --["IconFilePath"] = "model/01building/V3/components/base/tingzi02/tingzi02.x.png",
	--}
	--,
  --},
  --["BCS_02block"] = { -- 楼层
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "楼层1",
	  --["ModelFilePath"] = "model/01building/V3/components/block/block01/block01.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/block01/block01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "楼层2",
	  --["ModelFilePath"] = "model/01building/V3/components/block/block02/block02.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/block02/block02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房1",
	  --["ModelFilePath"] = "model/01building/V3/components/block/minfang01/minfang01.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/minfang01/minfang01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房2",
	  --["ModelFilePath"] = "model/01building/V3/components/block/minfang02/minfang02.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/minfang02/minfang02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房2b",
	  --["ModelFilePath"] = "model/01building/V3/components/block/minfang02b/minfang02b.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/minfang02b/minfang02b.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "塔1",
	  --["ModelFilePath"] = "model/01building/V3/components/block/ta01/ta01.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/ta01/ta01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋1",
	  --["ModelFilePath"] = "model/01building/V3/components/block/nanguawu01/nanguawu01.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/nanguawu01/nanguawu01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋2",
	  --["ModelFilePath"] = "model/01building/V3/components/block/nanguawu02/nanguawu02.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/nanguawu02/nanguawu02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "亭子1",
	  --["ModelFilePath"] = "model/01building/V3/components/block/tingzi01/tingzi01.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/tingzi01/tingzi01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "亭子2",
	  --["ModelFilePath"] = "model/01building/V3/components/block/tingzi02/tingzi02.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/tingzi02/tingzi02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "斜塔1",
	  --["ModelFilePath"] = "model/01building/V3/components/block/xieta01/xieta01.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/xieta01/xieta01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "斜塔2",
	  --["ModelFilePath"] = "model/01building/V3/components/block/xieta02/xieta02.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/xieta02/xieta02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "斜塔3",
	  --["ModelFilePath"] = "model/01building/V3/components/block/xieta03/xieta03.x",
	  --["IconFilePath"] = "model/01building/V3/components/block/xieta03/xieta03.x.png",
	--}
	--,
  --},
  --["BCS_03blocktop"] = { -- 房顶
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "房顶1",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/blocktop01/blocktop01.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/blocktop01/blocktop01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "房顶2",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/blocktop02/blocktop02.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/blocktop02/blocktop02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "房顶3",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/blocktop03/blocktop03.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/blocktop03/blocktop03.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "房顶4",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/blocktop04/blocktop04.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/blocktop04/blocktop04.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房1",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/minfang01/minfang01.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/minfang01/minfang01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房2",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/minfang02/minfang02.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/minfang02/minfang02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "塔1",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/ta01/ta01.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/ta01/ta01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "亭子1",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/tingzi01/tingzi01.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/tingzi01/tingzi01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "亭子2",
	  --["ModelFilePath"] = "model/01building/V3/components/blocktop/tingzi02/tingzi02.x",
	  --["IconFilePath"] = "model/01building/V3/components/blocktop/tingzi02/tingzi02.x.png",
	--}
	--,
  --},
  --["BCS_04stairs"] = { -- 楼梯
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "楼梯1",
	  --["ModelFilePath"] = "model/01building/V3/components/stairs/stairs01/stairs01.x",
	  --["IconFilePath"] = "model/01building/V3/components/stairs/stairs01/stairs01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "楼梯2",
	  --["ModelFilePath"] = "model/01building/V3/components/stairs/stairs02/stairs02.x",
	  --["IconFilePath"] = "model/01building/V3/components/stairs/stairs02/stairs02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "楼梯3",
	  --["ModelFilePath"] = "model/01building/V3/components/stairs/stairs03/stairs03.x",
	  --["IconFilePath"] = "model/01building/V3/components/stairs/stairs03/stairs03.x.png",
	--}
	--,
  --},
  --["BCS_05door"] = { -- 门
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "门",
	  --["ModelFilePath"] = "model/01building/V3/components/door/door01/door01.x",
	  --["IconFilePath"] = "model/01building/V3/components/door/door01/door01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "门2",
	  --["ModelFilePath"] = "model/01building/V3/components/door/door02/door02.x",
	  --["IconFilePath"] = "model/01building/V3/components/door/door02/door02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房1",
	  --["ModelFilePath"] = "model/01building/V3/components/door/minfang01/minfang01.x",
	  --["IconFilePath"] = "model/01building/V3/components/door/minfang01/minfang01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房1b",
	  --["ModelFilePath"] = "model/01building/V3/components/door/minfang01b/minfang01b.x",
	  --["IconFilePath"] = "model/01building/V3/components/door/minfang01b/minfang01b.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋1",
	  --["ModelFilePath"] = "model/01building/V3/components/door/nanguawu01/nanguawu01.x",
	  --["IconFilePath"] = "model/01building/V3/components/door/nanguawu01/nanguawu01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋2",
	  --["ModelFilePath"] = "model/01building/V3/components/door/nanguawu02/nanguawu02.x",
	  --["IconFilePath"] = "model/01building/V3/components/door/nanguawu02/nanguawu02.x.png",
	--}
	--,
  --},
  --["BCS_06window"] = { -- 窗户
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户1",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window01/window01.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window01/window01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户2",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window02/window02.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window02/window02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋1",
	  --["ModelFilePath"] = "model/01building/V3/components/window/nanguawu01/nanguawu01.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/nanguawu01/nanguawu01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋2",
	  --["ModelFilePath"] = "model/01building/V3/components/window/nanguawu02/nanguawu02.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/nanguawu02/nanguawu02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户3",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window03/window03.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window03/window03.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户4",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window04/window04.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window04/window04.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户5",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window05/window05.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window05/window05.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户6",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window06/window06.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window06/window06.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户7",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window07/window07.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window07/window07.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户8",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window08/window08.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window08/window08.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户9",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window09/window09.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window09/window09.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "窗户10",
	  --["ModelFilePath"] = "model/01building/V3/components/window/window10/window10.x",
	  --["IconFilePath"] = "model/01building/V3/components/window/window10/window10.x.png",
	--}
	--,
  --},
  --["BCS_07chimney"] = { -- 烟囱
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "烟囱1",
	  --["ModelFilePath"] = "model/01building/V3/components/chimney/chimney01/chimney01.x",
	  --["IconFilePath"] = "model/01building/V3/components/chimney/chimney01/chimney01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "烟囱2",
	  --["ModelFilePath"] = "model/01building/V3/components/chimney/chimney02/chimney02.x",
	  --["IconFilePath"] = "model/01building/V3/components/chimney/chimney02/chimney02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "烟囱3",
	  --["ModelFilePath"] = "model/01building/V3/components/chimney/chimney03/chimney03.x",
	  --["IconFilePath"] = "model/01building/V3/components/chimney/chimney03/chimney03.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房1",
	  --["ModelFilePath"] = "model/01building/V3/components/chimney/minfang01/minfang01.x",
	  --["IconFilePath"] = "model/01building/V3/components/chimney/minfang01/minfang01.x.png",
	--}
	--,
  --},
  --["BCS_08deco"] = { -- 装饰
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "装饰1",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/deco01/deco01.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/deco01/deco01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "装饰2",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/deco02/deco02.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/deco02/deco02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "装饰3",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/deco03/deco03.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/deco03/deco03.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房1",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/minfang01/minfang01.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/minfang01/minfang01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房2",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/minfang02/minfang02.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/minfang02/minfang02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房2b",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/minfang02b/minfang02b.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/minfang02b/minfang02b.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房2c",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/minfang02c/minfang02c.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/minfang02c/minfang02c.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "民房2d",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/minfang02d/minfang02d.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/minfang02d/minfang02d.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋1",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/nanguawu01/nanguawu01.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/nanguawu01/nanguawu01.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "南瓜屋2",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/nanguawu02/nanguawu02.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/nanguawu02/nanguawu02.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "R4",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "塔1",
	  --["ModelFilePath"] = "model/01building/V3/components/deco/ta01/ta01.x",
	  --["IconFilePath"] = "model/01building/V3/components/deco/ta01/ta01.x.png",
	--}
	--,
  --},
  
  ["CCS_01original"] = { -- CCS
	  {
	  ["Reserved4"] = "Human/Male",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "男人类",
	  ["ModelFilePath"] = "character/v3/Human/Male/HumanMale.x",
	  ["IconFilePath"] = "character/v3/Human/Male/HumanMale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Human/Female",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "女人类",
	  ["ModelFilePath"] = "character/v3/Human/Female/HumanFemale.x",
	  ["IconFilePath"] = "character/v3/Human/Female/HumanFemale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Angel/Male",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "男天使",
	  ["ModelFilePath"] = "character/v3/Angel/Male/AngelMale.x",
	  ["IconFilePath"] = "character/v3/Angel/Male/AngelMale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Angel/Female",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "女天使",
	  ["ModelFilePath"] = "character/v3/Angel/Female/AngelFemale.x",
	  ["IconFilePath"] = "character/v3/Angel/Female/AngelFemale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Momo/Male",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "男momo",
	  ["ModelFilePath"] = "character/v3/Momo/Male/MomoMale.x",
	  ["IconFilePath"] = "character/v3/Momo/Male/MomoMale.x.png",
	}
	,
	  --{
	  --["Reserved4"] = "Momo/Female",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "女momo",
	  --["ModelFilePath"] = "character/v3/Momo/Female/MomoFemale.x",
	  --["IconFilePath"] = "character/v3/Momo/Female/MomoFemale.x.png",
	--}
	--,
	  --{
	  --["Reserved4"] = "Horse/Male",
	  --["Reserved3"] = "R3",
	  --["Reserved1"] = "R1",
	  --["Reserved2"] = "R2",
	  --["Price"]=50,
	  --["IconAssetName"] = "公马",
	  --["ModelFilePath"] = "character/v3/Horse/Male/HorseMale.x",
	  --["IconFilePath"] = "character/v3/Horse/Male/HorseMale.x.png",
	--}
	--,
	  {
	  ["Reserved4"] = "Horse/Female",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "母马",
	  ["ModelFilePath"] = "character/v3/Horse/Female/HorseFemale.x",
	  ["IconFilePath"] = "character/v3/Horse/Female/HorseFemale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Witch/Female",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "小女巫",
	  ["ModelFilePath"] = "character/v3/Witch/Female/WitchFemale.x",
	  ["IconFilePath"] = "character/v3/Witch/Female/WitchFemale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Witch2/Female",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "小女巫",
	  ["ModelFilePath"] = "character/v3/Witch2/Female/Witch2Female.x",
	  ["IconFilePath"] = "character/v3/Witch2/Female/Witch2Female.x.png",
	}
	,
  },
  ["CCS_02test"] = { -- CCSTest
	  {
	  ["Reserved4"] = "Child/Male",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "小男孩",
	  ["ModelFilePath"] = "character/v3/Child/Male/ChildMale.x",
	  ["IconFilePath"] = "character/v3/Child/Male/ChildMale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Child/Female",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "小女孩",
	  ["ModelFilePath"] = "character/v3/Child/Female/ChildFemale.x",
	  ["IconFilePath"] = "character/v3/Child/Female/ChildFemale.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Human2/Male",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "男青年",
	  ["ModelFilePath"] = "character/v3/Human2/Male/Human2Male.x",
	  ["IconFilePath"] = "character/v3/Human2/Male/Human2Male.x.png",
	}
	,
	  {
	  ["Reserved4"] = "Human2/Female",
	  ["Reserved3"] = "R3",
	  ["Reserved1"] = "R1",
	  ["Reserved2"] = "R2",
	  ["Price"]=50,
	  ["IconAssetName"] = "小女孩",
	  ["ModelFilePath"] = "character/v3/Human2/Female/Human2Female.x",
	  ["IconFilePath"] = "character/v3/Human2/Female/Human2Female.x.png",
	}
	,
  },
  
  --["TestLvl2"] = { -- My Favorites/TestLvl2
	  --{
	--}
	--,
  --},
  --["TestLvl3"] = { -- My Favorites/TestLvl2/TestLvl3
	  --{
	--}
	--,
  --},
  --["TestLvl4"] = { -- My Favorites/TestLvl2/TestLvl3/TestLvl4
	  --{
	--}
	--,
  --},
  --
  --["WishlistTest"] = { -- My Wishlist/WishlistTest
	  --{
	--}
	--,
  --},
}
