--[[
Title:
Author(s): Leio
Date: 2010/04/19
Desc:
use the lib:
------------------------------------------------------------
NPL.load("(gl)script/apps/Aries/Mail/MailList.lua");
id = 10000,
name = "",
title_bg = "",
npc_bg = "",
mail_page = "",
sendtime = "00:02:00",
sender = "",
content = ,
gotoPosition = ,
cameraPosition = ,
canSendFunc = ,
		
------------------------------------------------------------
]]
NPL.load("(gl)script/apps/Aries/Mail/MailState.lua");
local MailList = commonlib.gettable("MyCompany.Aries.Quest.Mail.MailList");


-- push the mail to auto tip. 
-- @note: assign this to mail.pre_send_func.
-- @return false if ordinary mail should be surpressed 
local function PushToAutoTip(mail)
	NPL.load("(gl)script/apps/Aries/Desktop/Dock/AutoTips.lua");
	local AutoTips = commonlib.gettable("MyCompany.Aries.Desktop.AutoTips");
end
local function is(realname,a,b)
	if(realname)then
		return a;
	else
		return b;
	end

end
MailList.RealNameContent = {
	[9033] = {
		content_realname = "你今天已经在哈奇小镇玩了3个小时。<br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
		content = "你今天已经在哈奇小镇玩了3个小时。3小时后，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
	},
	[9034] = {
		content_realname = "你今天已经在哈奇小镇玩了3个小时。<br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
		content = "你今天已经在哈奇小镇玩了3个小时。3小时后，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
	},
	[9035] = {
		content_realname = "你今天已经在哈奇小镇玩了4个小时。<br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
		content = "你今天已经在哈奇小镇玩了4个小时。3-5小时，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
	},
	[9036] = {
		content_realname = "你今天已经在哈奇小镇玩了4个半小时。<br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
		content = "你今天已经在哈奇小镇玩了4个半小时。3-5小时，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。",
	},
	[9037] = {
		content_realname = "你今天已经在哈奇小镇玩了5个小时。<br />上网太长时间，对眼睛和身体都不好。赶快休息一下，或者去复习一下功课吧。明天再来继续哈奇小镇的精彩之旅。",
		content = "你今天已经在哈奇小镇玩了5个小时。游戏经验和收益被取消了。 <br />上网太长时间，对眼睛和身体都不好。赶快休息一下，或者去复习一下功课吧。明天再来继续哈奇小镇的精彩之旅。",
	},
	[9038] = {
		content_realname = "你今天已经在哈奇小镇玩了6个小时。<br />上网太长时间，对眼睛和身体都不好。赶快休息一下，或者去复习一下功课吧。明天再来继续哈奇小镇的精彩之旅。",
		content = "你今天已经在哈奇小镇玩了6个小时。任务经验被取消了。 <br />上网太长时间，对眼睛和身体都不好。赶快休息一下，或者去复习一下功课吧。明天再来继续哈奇小镇的精彩之旅。",
	},
}
--系统邮件
MailList.SystemTimerMails = {
	[8000]  ={
		name = "赠送礼物成功",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_GiftRemind.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = nil,
		content = "我留下了一点小礼物在你的礼物盒里，希望你能喜欢哦！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[8001]  ={
		name = "赠送礼物失败",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_GiftRemind.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = nil,
		content = "我想送礼物给你，可是你的礼物盒已经满了，不能再收礼物了。快去清理一下礼物盒吧。",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[8002]  ={
		name = "抱抱龙成长到5级",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你的抱抱龙长大了，也该让他去学点本领啦！雪山顶的技能学院正在教建造技能，快带他去好好学习吧！",
		gotoPosition = nil;--{ 19955.2421875, 128.53883361816, 20459.8515625},
		cameraPosition = { 8.857349, 0.592088,  -0.125364, },
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[9030]  ={
		name = "今天总共在线时间 45分钟",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "00:45:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你已经在哈奇小镇玩了45分钟，是不是已经坐累了？上网太长时间，对眼睛和身体都不好。<br />快快站起身来，活动一下身体，做做眼保健操吧。",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9031]  ={
		name = "今天总共在线时间 90分钟",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "01:30:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你已经在哈奇小镇玩了90分钟，是不是已经坐累了？上网太长时间，对眼睛和身体都不好。<br />快快站起身来，活动一下身体，做做眼保健操吧。",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9032]  ={
		name = "今天总共在线时间135分钟",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "02:15:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你已经在哈奇小镇玩了145分钟，是不是已经坐累了？上网太长时间，对眼睛和身体都不好。<br />快快站起身来，活动一下身体，做做眼保健操吧。",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9033]  ={
		name = "今天总共在线时间 3小时",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "03:00:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你今天已经在哈奇小镇玩了3个小时。3小时后，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。", 
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9034]  ={
		name = "今天总共在线时间 3.5小时",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "03:30:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你今天已经在哈奇小镇玩了3个小时。3小时后，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。", 
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9035]  ={
		name = "今天总共在线时间 4小时",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "04:00:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你今天已经在哈奇小镇玩了4个小时。3-5小时，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。", 
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9036]  ={
		name = "今天总共在线时间 4.5小时",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "04:30:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你今天已经在哈奇小镇玩了4个半小时。3-5小时，战斗经验、宠物经验、奇豆、战利品减半。 <br />上网太长时间，对眼睛和身体都不好。明天再来继续哈奇小镇的精彩之旅。", 
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9037]  ={
		name = "今天总共在线时间 5小时",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "05:00:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你今天已经在哈奇小镇玩了5个小时。游戏经验和收益被取消了。 <br />上网太长时间，对眼睛和身体都不好。赶快休息一下，或者去复习一下功课吧。明天再来继续哈奇小镇的精彩之旅。", 
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9038]  ={
		name = "今天总共在线时间 6小时",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "06:00:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你今天已经在哈奇小镇玩了6个小时。任务经验被取消了。 <br />上网太长时间，对眼睛和身体都不好。赶快休息一下，或者去复习一下功课吧。明天再来继续哈奇小镇的精彩之旅。", 
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[9004]  ={
		name = "现在时间是 21:00:00",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = "21:00:00",
		sender = "哈奇小镇管理处",
		content = "熬夜加班是星星和月亮的事，你要早点休息了哦！现在都21：00啦，快快刷牙，洗脸，早点休息吧，明天一定又是幸福快乐的一天！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[9005]  ={
		name = "现在时间是 23:45:00",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = "23:45:00",
		sender = "哈奇小镇管理处",
		content = "这里的夜晚静悄悄啦，小哈奇也该上床休息了哦！为了小哈奇正常的作息，并且不影响明天的学习生活，公民管理处把哈奇小镇的开放时间设定为6：00-24：00，现在还有15分钟哦！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	[9006]  ={
		name = "现在时间是 23:55:00",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = "23:55:00",
		sender = "哈奇小镇管理处",
		content = "这里的夜晚静悄悄啦，小哈奇也该上床休息了哦！为了小哈奇正常的作息，并且不影响明天的学习生活，公民管理处把哈奇小镇的开放时间设定为6：00-24：00，现在还有5分钟哦！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
		pre_send_func = PushToAutoTip,
	},
	--[10000]  ={
		--name = "水晶兔",
		--title_bg = [[<div style="margin-left:0px;margin-top:0px;width:512px;height:128px;background:url(Texture/Aries/PENote/title_crystalbunny_32bits.png# 0 0 512 128)" />]],
		--npc_bg = [[<div style="margin-left:0px;margin-top:80px;width:220px;height:220px;background:url(Texture/Aries/Quest/CrystalBunny/bunny_32bits.png# 0 0 220 220)" />]],
		--mail_page = nil,
		--sendtime = "00:02:00",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "水晶兔",
		--content = "我是帮多克特博士制造怪怪蛋的水晶兔，但是我犯了一个大错，我不知道该怎么弥补，我不敢见到多克特博士，他肯定会教训我的，谁来帮帮我呀！呜呜呜~",
		--gotoPosition = nil;--{ 19876.5625, 8.8073348999023, 20098.9375  },
		--cameraPosition = { 8.857349395752, 0.40253412723541, 0.91224783658981 },
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_CrystalBunny,
	--},
	--[10001]  ={
		--name = "郁闷的巴斯",
		--title_bg = [[<div style="margin-left:0px;margin-top:0px;width:338px;height:115px;background:url(Texture/Aries/PENote/title_barth_32bits.png# 0 0 338 115)" />]],
		--npc_bg = [[<div style="margin-left:0px;margin-top:80px;width:256px;height:256px;background:url(Texture/Aries/PENote/npcs/barth_32bits.png# 0 0 256 256)" />]],
		--mail_page = nil,
		--sendtime = "00:02:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "巴斯",
		--content = "我是最忧郁的巴斯，一直在龙龙乐园的医院这里修养，其实我是得了心病，这段日子都是苏菲姐姐在照顾我，可是她也不能帮我找回我以前丢失的玩具人。你能帮我找一些玩具零件吗，也许我能再做一个玩具人。",
		--gotoPosition = nil;--{ 19972.65625, 0.45999786257744, 19835.29296875  },
		--cameraPosition = { 7.4928288459778, 0.51981174945831, 1.2739082574844 },
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_DepressedBarth,
	--},
	-- 2010.10.1: update old user to new version. 
	[10002]  ={
		name = "哈奇战斗通知",
		title_bg = [[<div style="margin-left:-30px;margin-top:0px;width:563px;height:115px;background:url(Texture/Aries/PENote/penote_title_2_32bits.png# 0 0 580 115)" />]],
		npc_bg = [[<div style="margin-left:0px;margin-top:40px;width:256px;height:256px;background:url(Texture/Aries/PENote/npcs/alcalde_32bits.png)" />]],
		mail_page = nil,
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "罗德镇长",
		content = "在暗黑魔王企图用傀儡术控制其他生物，统治整个世界的危险时刻；唯一能对傀儡术免疫的抱抱龙们激发出了前所未有的潜力，所有的小龙蛋们破壳而出，不再有生病与死亡；同时，为了保护哈奇，他们把魔法和天赋都无私转移到了哈奇身上；以后，保卫哈奇小镇，打倒魔王，拯救世界的重任就交给你们了！！！",
		gotoPosition = nil;
		cameraPosition = { 7.4928288459778, 0.51981174945831, 1.2739082574844 },
		canSendFunc = nil,
	},
	[10003]  ={
		name = "温馨提醒: 在线5小时候, 每15分钟提醒一次",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = "00:15:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "罗德镇长",
		content = "你今天的战斗时间已经用完咯，感谢你的热心帮助，做个眼保健操，扭扭脖子，把作业做完了，明天再来保卫小镇吧！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = 1000,
		canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_Anti,
	},
	[10011]  ={
		name = "魔法星升级 0 - 1",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "感谢你让我成为充满能量的魔法星！我一定会用我心陪伴你，守护你，用我神奇的魔法帮你建设哈奇小镇！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10012]  ={
		name = "魔法星升级 2",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "在你的精心照顾下，我又长大一些，已经2级啦！我的魔法也更强了，我会在魔法储蓄罐里为你存下更多的奇豆！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10013]  ={
		name = "魔法星升级 3",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "在你的精心照顾下，我又长大一些，已经3级啦！我的魔法也更强了，我会在魔法口袋里帮你收集更多的礼物！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10014]  ={
		name = "魔法星升级 4",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "在你的精心照顾下，我又长大一些，已经4级啦！我的魔法也更强了，我一定会用我所有的魔法陪伴你，守护你！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10015]  ={
		name = "魔法星升级 5",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "真不敢相信，我已经5级了，这都是你的功劳！我的魔法也一直在随我的等级一起成长！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10016]  ={
		name = "魔法星升级 6",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "我现在已经6级了！我目前的魔法能让你额外获得更多的经验和魔法卡片，这都是你的功劳！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10017]  ={
		name = "魔法星升级 7",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "在你的精心培养下，我又升了一级，已经7级啦！我感觉到我体内的魔法力量越来越强烈了！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10018]  ={
		name = "魔法星升级 8",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "我已经不是一颗普通的魔法星了，我体内的魔力正在逐渐强大，只有8级的魔法星才有这样神奇的力量哦！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10019]  ={
		name = "魔法星升级 9",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "真不敢相信！我已经9级了，我现在是一颗拥有超强魔法力量的魔法星，我相信我很快就会拥有顶级的魔法力量了！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10020]  ={
		name = "魔法星升级 10",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar.html",
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "我已经10级了！我目前拥有最高级的魔法力量，现在的我虽然魔力强大，但是也很脆弱，相信你能照顾好我，我想把我最强大的魔力贡献给最贴心的你！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10021]  ={
		name = "即将到期的邮件提醒:当魔法星能量值大于0，小于6",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar_Remind.html",
		sendtime = "00:02:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "我感到自己的能量值正在减弱，当我的能量值减到0的时候，我就会变成一块冰冷的石头，再也不能用魔法守护你了。我真不愿离开你！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_MagicStar_Energe_0_6,
	},
	[10022]  ={
		name = "初次到期的邮件提醒:当魔法星能量值等于0，且上次登陆时能量值大于0",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar_Remind.html",
		sendtime = "00:02:00",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "你的魔法星",
		content = "我的能量值已经消耗殆尽，我已经变成了一块冰冷的石头，再也不能用魔法守护你了！你依旧是我永远的好主人！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_MagicStar_Energe_0,
	},
	[10023]  ={
		name = "开通魔法星的邮件提醒:当魔法星能量值从0变为非0",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_MagicStar_Remind.html",
		sendtime = mil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "魔法学院",
		content = "你的好友用户昵称（米米号）的魔法星已经复活了，它拥有神奇的魔法，以后有什么事情可以找他帮忙哦！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10024]  ={
		name = "当每次升级获得训练点时，需要邮件提示",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = mil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "魔法学院",
		content = "恭喜你现在升到XX级，可以获得一个训练点，当你升到XX级，将获得下一个训练点。每次升到可获得训练点的级别即下发此邮件。训练点可以用来学习非本系的魔法， 快去哈奇岛的魔法学院找龙导师们学习新魔法吧！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10025]  ={
		name = "哈奇小镇小调查 2010-12-10 到 2010-12-16",
		title_bg = [[<div style="margin-left:0px;margin-top:0px;width:442px;height:115px;background:url(Texture/Aries/PENote/penote_title_children_research_32bits.png# 0 0 442 115)" />]],
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_1210_1016_Research.html",
		sendtime = "00:00:20",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "",
		content = "",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_Research_2010_12_10,
	},
	[10026]  ={
		name = "当A根据B的链接引入哈奇小镇后，B将收到管理处邮件提示",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_RedFruit.html",
		page_params = {id = 10026, state = 0},
		sendtime = mil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = " 哈奇小镇管理处",
		content = "在你的热情邀请下，[用户名/米米号]（说明：带链接，可以点开）也来哈奇小镇居住啦！同时你也获得了1颗红心果，记得常联系他哦！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10027]  ={
		name = "当A的抱抱龙长到3级时，B将收到管理处邮件提示",
		title_bg = nil,
		npc_bg = nil,
		mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_RedFruit.html",
		page_params = {id = 10027, state = 1},
		sendtime = mil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = " 哈奇小镇管理处",
		content = " 在你的热情帮助下，[用户名/米米号]的的战斗等级已经达到3级了，你真是快乐的传播大使， 2颗红心果已经发放给你啦，记得去兑换礼物哦，相信你也一定能把快乐传播给更多人的！  ",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10028]  ={
		name = "拉升级活动---黄金新手礼包活动",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		page_params = nil,
		sendtime = nil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = " 你真棒，已经XX级了，记得打开黄金新手礼包领取奖品哦，就在你的背包里，注意查看哦！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
	[10029]  ={
		name = "摇摇幸运树提醒",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		-- sendtime = "00:00:10",
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "哈奇小镇管理处",
		content = "你今天还有一次空手摇摇幸运树的机会哦，100%能获得经验面包和其他宝贝呢，机不可失，赶紧去看看吧！",
		gotoPosition = {20035.68,2.56,19716.35},
		cameraPosition = {8.86,0.27,2.95},
		sendnum = nil,
		sendmaxnum = nil,
		-- canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_LuckyTree,
	},
	--[10030]  ={
		--name = "新年红包 2011-02-04",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:50px;margin-top:50px;width:227px;height:254px;background:url(Texture/Aries/PENote/npcs/alcalde_32bits.png# 0 0 227 254)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-04" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "罗德镇长",
		--content = "兔年来了，罗德镇长来给你拜年了！,<br/>年年岁岁又年年，新的一年又起航。将所有的苦辣留在昨天，用所有的快乐和幸福畅享新的一年。愿你在新的一年里万事顺心如意！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-04",
	--},
	--[10031]  ={
		--name = "新年红包 2011-02-05",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:50px;width:254px;height:201px;background:url(Texture/Aries/PENote/npcs/qinglong_32bits.png# 0 0 254 201)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-05" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "青龙",
		--content = "新年快乐，青龙来给勇者哈奇拜年了！<br/>新的一年，祝你的魔法技能更上一层楼，成为最顶级的魔法师！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-05",
	--},
	--[10032]  ={
		--name = "新年红包 2011-02-06",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:50px;width:219px;height:241px;background:url(Texture/Aries/PENote/npcs/storm_32bits.png# 0 0 219 241)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-06" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "高登",
		--content = "兔年来了，风暴系魔法导师来跟你拜年了！<br/>新的一年，祝你新年快乐，健健康康！在魔法能力上，祝愿你越来越强！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-06",
	--},
	--[10033]  ={
		--name = "新年红包 2011-02-07",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:50px;width:181px;height:237px;background:url(Texture/Aries/PENote/npcs/fire_32bits.png# 0 0 181 237)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-07" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "伏尔坎",
		--content = "新年快乐！烈火系导师伏尔坎给你拜年了！<br/>祝愿你在新的一年红红火火，开开心心，成为最优秀的魔法师！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-07",
	--},
	--[10034]  ={
		--name = "新年红包 2011-02-08",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:50px;width:245px;height:240px;background:url(Texture/Aries/PENote/npcs/ice_32bits.png# 0 0 245 240)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-08" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "艾米娜",
		--content = "新年寒冰系导师艾米娜给你拜年了！<br/>兔年欢愉声声祝福，丝丝情谊，串串思念，化作一份礼品，留在你的心田，祝兔年欢愉，万事如意！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-08",
	--},
	--[10035]  ={
		--name = "新年红包 2011-02-09",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:50px;width:252px;height:239px;background:url(Texture/Aries/PENote/npcs/life_32bits.png# 0 0 252 239)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-09" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "爱丽丝",
		--content = "新年好！爱丽丝来给你拜年啦！<br/>新年快乐！祝你在新的一年继续保持着一颗善良的心，继续团结友爱下去，这样你很快就能成为最棒的魔法师啦！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-09",
	--},
	--[10036]  ={
		--name = "新年红包 2011-02-10",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:50px;width:250px;height:215px;background:url(Texture/Aries/PENote/npcs/death_32bits.png# 0 0 250 215)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-10" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "磊奥",
		--content = "新年好！磊奥给你拜年来啦！<br/>新年快乐！给你温暖，给你温馨，给你祝福。祝你运气像雨点一样密集，幸福像蜂蜜一样甜蜜。",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-10",
	--},
	--[10037]  ={
		--name = "新年红包 2011-02-11",
		--title_bg = nil,
		--npc_bg = nil,
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-11" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "帕帕",
		--content = "兔年到，帕帕祝福到！<br/>新年眼看就要到了，我托空气为邮差，把热腾腾的问候装订成包裹，印上真心为邮戳，37度恒温快递，收件人是你，真心祝你：新春好！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-11",
	--},
	--[10038]  ={
		--name = "新年红包 2011-02-12",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:0px;width:256px;height:275px;background:url(Texture/Aries/PENote/npcs/faster_32bits.png# 0 0 256 275)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-12" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "法斯特船长",
		--content = "新的一年，更适合冒险，法斯特船长来给你拜年了！<br/>祝你魔法力量更上一层楼，成为更出色的探险家！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-12",
	--},
	--[10039]  ={
		--name = "新年红包 2011-02-13",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:0px;width:193px;height:339px;background:url(Texture/Aries/PENote/npcs/susu_32bits.png# 0 0 193 339)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-13" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "苏苏",
		--content = "今天苏苏来给你拜年了！<br/>年年辞旧，岁岁迎新，光阴似箭，日月如梭，春节只有半月多，我的祝福天天有，新年好运，得心应手，笑口常开，青春永驻。",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-13",
	--},
	--[10040]  ={
		--name = "新年红包 2011-02-14",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:0px;width:254px;height:362px;background:url(Texture/Aries/PENote/npcs/hill_32bits.png# 0 0 254 362)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-14" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "希尔警长",
		--content = "新年到，希尔警长代表所有警员祝你新年快乐！<br/>新的一年，希望你在小镇开开心心，继续英明神武下去吧！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-14",
	--},
	--[10041]  ={
		--name = "新年红包 2011-02-15",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:0px;width:167px;height:379px;background:url(Texture/Aries/PENote/npcs/wudi_32bits.png# 0 0 167 379)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-15" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "伍迪",
		--content = "新年万事如意！伍迪祝你新年快乐！<br/>让好运围绕着你，幸福追着你，好心情天天陪伴你，祝你新年快乐!",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-15",
	--},
	--[10042]  ={
		--name = "新年红包 2011-02-16",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:0px;width:221px;height:305px;background:url(Texture/Aries/PENote/npcs/qingqing_32bits.png# 0 0 221 305)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-16" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "青青",
		--content = "新年到，青青祝你新年亏啊了！<br/>新春佳节， 祝你兔年大吉大利，大显身手！欢迎你到沙漠古堡来冒险哦！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-16",
	--},
	--[10043]  ={
		--name = "新年红包 2011-02-17",
		--title_bg = nil,
		--npc_bg = [[<div style="margin-left:0px;margin-top:0px;width:178px;height:350px;background:url(Texture/Aries/PENote/npcs/dongdong_32bits.png# 0 0 178 350)" />]],
		--mail_page = "script/apps/Aries/Mail/MailTemplate/Mail_Template_HappyNewYear_2011.html",
		--page_params = { gift_date = "2011-02-17" },
		--sendtime = "00:00:10",
		--send_exact_date = nil,
		--send_exact_time = nil,
		--sender = "冬冬",
		--content = "新年到，咚咚锵，咚咚锵，冬冬来给你拜年了！<br/>新的一年祝你和你的抱抱龙快乐，天天能上英雄排行榜！",
		--gotoPosition = nil,
		--cameraPosition = nil,
		--sendnum = nil,
		--sendmaxnum = nil,
		--canSendFunc = MyCompany.Aries.Quest.Mail.MailState.CanSend_HappyNewYear_2011,
		--canSend_params = "2011-02-17",
	--},
	[10044]  ={
		name = "当战斗力提升到新阶段时，需要邮件提示",
		title_bg = nil,
		npc_bg = nil,
		mail_page = nil,
		sendtime = mil,
		send_exact_date = nil,
		send_exact_time = nil,
		sender = "红蘑菇使者",
		content = "恭喜你的战斗力达到%d，可以参加红蘑菇1v1 %s 组的比赛了，快去和其他小哈奇一决胜负吧！",
		gotoPosition = nil,
		cameraPosition = nil,
		sendnum = nil,
		sendmaxnum = nil,
		canSendFunc = nil,
	},
}